export default {
    ActiveProjects: [
        {
            id: 1,
            title: "NASA warns of horrific solar flares! Earth will be impacted",
            Script: "Done",
            VoiceOver: "Approval",
            video: "working on it",
            Thumbnail: "working on it",
            channelName: "CYCLING RIGHT NOW",
            ScriptAssigned: "Jaitn Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Jaitn Rai",
            ThumbnailAssignedToMe: true,
            ScriptUploaded: true,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false,
        },
        {
            id: 2,
            title: "China Rocket Crashes Back on Earth, Draws NASA Rebuke",
            Script: "Done",
            VoiceOver: "working on it",
            video: "working on it",
            Thumbnail: "working on it",
            channelName: "CYCLING NEWS LIVE",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 3,
            title: "Israeli high-tech on edge as Wall Street storm approaches",
            Script: "Done",
            VoiceOver: "Done",
            video: "working on it",
            Thumbnail: "stuck",
            channelName: "TATE NATION",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 4,
            title: "NASA warns of horrific solar flares! Earth will be impacted",
            Script: "Done",
            VoiceOver: "Approval",
            video: "working on it",
            Thumbnail: "working on it",
            channelName: "TATE NATION",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 5,
            title: "China Rocket Crashes Back on Earth, Draws NASA Rebuke",
            Script: "Done",
            VoiceOver: "working on it",
            video: "working on it",
            Thumbnail: "working on it",
            channelName: "FORMULA1 LIVE",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 6,
            title: "Israeli high-tech on edge as Wall Street storm approaches",
            Script: "Done",
            VoiceOver: "Done",
            video: "working on it",
            Thumbnail: "stuck",
            channelName: "FORMULA1 LIVE",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 7,
            title: "China Rocket Crashes Back on Earth, Draws NASA Rebuke",
            Script: "Done",
            VoiceOver: "working on it",
            video: "working on it",
            Thumbnail: "working on it",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 8,
            title: "Israeli high-tech on edge as Wall Street storm approaches",
            Script: "Done",
            VoiceOver: "Done",
            video: "working on it",
            Thumbnail: "stuck",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 9,
            title: "NASA warns of horrific solar flares! Earth will be impacted",
            Script: "Done",
            VoiceOver: "Approval",
            video: "working on it",
            Thumbnail: "working on it",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 10,
            title: "China Rocket Crashes Back on Earth, Draws NASA Rebuke",
            Script: "Done",
            VoiceOver: "working on it",
            video: "working on it",
            Thumbnail: "working on it",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 11,
            title: "Israeli high-tech on edge as Wall Street storm approaches",
            Script: "Done",
            VoiceOver: "Done",
            video: "working on it",
            Thumbnail: "stuck",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
        {
            id: 13,
            title: "NASA warns of horrific solar flares! Earth will be impacted",
            Script: "Done",
            VoiceOver: "Approval",
            video: "working on it",
            Thumbnail: "working on it",
            ScriptAssigned: "Jaitin Rai",
            ScriptAssignedToMe: true,
            VoiceOverAssigned: "Tonmoy Ghosh",
            VoiceOverAssignedToMe : false,
            VideoAssigned: "Rajkiran kalowar",
            VideoAssignedToMe: false,
            ThumbnailAssigned: "Anamika Biswas",
            ThumbnailAssignedToMe: false,
            ScriptUploaded: false,
            VoiceOverUploaded: false,
            VideoUploaded: false,
            ThumbnailUploaded: false
        },
    ],

    FinishedProjects: [
        {
            id: 1,
            title: "NASA warns of horrific solar flares! Earth will be impacted",
            Script: "Done",
            VoiceOver: "Approval",
            video: "working on it",
            Thumbnail: "working on it",
            uploaded: false
        },
        {
            id: 2,
            title: "China Rocket Crashes Back on Earth, Draws NASA Rebuke",
            Script: "Done",
            VoiceOver: "working on it",
            video: "working on it",
            Thumbnail: "working on it",
            uploaded: true
        },
        {
            id: 3,
            title: "Israeli high-tech on edge as Wall Street storm approaches",
            Script: "Done",
            VoiceOver: "Done",
            video: "working on it",
            Thumbnail: "stuck",
            uploaded: false
        },
        {
            id: 4,
            title: "Why Team Jumbo Visma is UNBEATABLE this year",
            Script: "Done",
            VoiceOver: "Approval",
            video: "working on it",
            Thumbnail: "working on it",
            uploaded: true
        },
        {
            id: 5,
            title: "How Jonas Vingegaard Won The Tour De France 2022?!",
            Script: "Done",
            VoiceOver: "working on it",
            video: "working on it",
            Thumbnail: "working on it",
            uploaded: true
        },
        {
            id: 6,
            title: "Peter Sagan, The ABSOLUTE KING Of Cycling!",
            Script: "Done",
            VoiceOver: "Done",
            video: "working on it",
            Thumbnail: "stuck",
            uploaded: true
        },
        {
            id: 7,
            title: "Top 10 Mass Sprints Of ALL TIME!",
            Script: "Done",
            VoiceOver: "working on it",
            video: "working on it",
            Thumbnail: "working on it",
            uploaded: true
        },
        {
            id: 8,
            title: "Israeli high-tech on edge as Wall Street storm approaches",
            Script: "Done",
            VoiceOver: "Done",
            video: "working on it",
            Thumbnail: "stuck",
            uploaded: true
        },
    ]

}